# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2013, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.3 on 2014-05-12 15:42:45.

require 'ads_common_for_bing_ads/savon_service'
require 'bing_ads_api/v9/campaign_management_service_registry'

module BingAdsApi; module V9; module CampaignManagementService
  class CampaignManagementService < AdsCommonForBingAds::SavonService
    def initialize(config, endpoint)
      namespace = 'https://bingads.microsoft.com/CampaignManagement/v9'
      super(config, endpoint, namespace, :V9)
    end

    def add_campaigns(*args, &block)
      return execute_action('add_campaigns', args, &block)
    end

    def get_campaigns_by_account_id(*args, &block)
      return execute_action('get_campaigns_by_account_id', args, &block)
    end

    def get_campaigns_by_ids(*args, &block)
      return execute_action('get_campaigns_by_ids', args, &block)
    end

    def delete_campaigns(*args, &block)
      return execute_action('delete_campaigns', args, &block)
    end

    def update_campaigns(*args, &block)
      return execute_action('update_campaigns', args, &block)
    end

    def get_negative_keywords_by_campaign_ids(*args, &block)
      return execute_action('get_negative_keywords_by_campaign_ids', args, &block)
    end

    def set_negative_keywords_to_campaigns(*args, &block)
      return execute_action('set_negative_keywords_to_campaigns', args, &block)
    end

    def get_negative_sites_by_campaign_ids(*args, &block)
      return execute_action('get_negative_sites_by_campaign_ids', args, &block)
    end

    def set_negative_sites_to_campaigns(*args, &block)
      return execute_action('set_negative_sites_to_campaigns', args, &block)
    end

    def add_ad_groups(*args, &block)
      return execute_action('add_ad_groups', args, &block)
    end

    def delete_ad_groups(*args, &block)
      return execute_action('delete_ad_groups', args, &block)
    end

    def get_ad_groups_by_ids(*args, &block)
      return execute_action('get_ad_groups_by_ids', args, &block)
    end

    def get_ad_groups_by_campaign_id(*args, &block)
      return execute_action('get_ad_groups_by_campaign_id', args, &block)
    end

    def submit_ad_group_for_approval(*args, &block)
      return execute_action('submit_ad_group_for_approval', args, &block)
    end

    def update_ad_groups(*args, &block)
      return execute_action('update_ad_groups', args, &block)
    end

    def get_negative_keywords_by_ad_group_ids(*args, &block)
      return execute_action('get_negative_keywords_by_ad_group_ids', args, &block)
    end

    def set_negative_keywords_to_ad_groups(*args, &block)
      return execute_action('set_negative_keywords_to_ad_groups', args, &block)
    end

    def get_negative_sites_by_ad_group_ids(*args, &block)
      return execute_action('get_negative_sites_by_ad_group_ids', args, &block)
    end

    def set_negative_sites_to_ad_groups(*args, &block)
      return execute_action('set_negative_sites_to_ad_groups', args, &block)
    end

    def add_targets_to_library(*args, &block)
      return execute_action('add_targets_to_library', args, &block)
    end

    def update_targets_in_library(*args, &block)
      return execute_action('update_targets_in_library', args, &block)
    end

    def delete_targets_from_library(*args, &block)
      return execute_action('delete_targets_from_library', args, &block)
    end

    def get_targets_info_from_library(*args, &block)
      return execute_action('get_targets_info_from_library', args, &block)
    end

    def get_targets_by_ids(*args, &block)
      return execute_action('get_targets_by_ids', args, &block)
    end

    def set_target_to_ad_group(*args, &block)
      return execute_action('set_target_to_ad_group', args, &block)
    end

    def delete_target_from_ad_group(*args, &block)
      return execute_action('delete_target_from_ad_group', args, &block)
    end

    def get_targets_by_ad_group_ids(*args, &block)
      return execute_action('get_targets_by_ad_group_ids', args, &block)
    end

    def set_target_to_campaign(*args, &block)
      return execute_action('set_target_to_campaign', args, &block)
    end

    def delete_target_from_campaign(*args, &block)
      return execute_action('delete_target_from_campaign', args, &block)
    end

    def get_targets_by_campaign_ids(*args, &block)
      return execute_action('get_targets_by_campaign_ids', args, &block)
    end

    def add_ads(*args, &block)
      return execute_action('add_ads', args, &block)
    end

    def delete_ads(*args, &block)
      return execute_action('delete_ads', args, &block)
    end

    def get_ads_by_editorial_status(*args, &block)
      return execute_action('get_ads_by_editorial_status', args, &block)
    end

    def get_ads_by_ids(*args, &block)
      return execute_action('get_ads_by_ids', args, &block)
    end

    def get_ads_by_ad_group_id(*args, &block)
      return execute_action('get_ads_by_ad_group_id', args, &block)
    end

    def update_ads(*args, &block)
      return execute_action('update_ads', args, &block)
    end

    def add_keywords(*args, &block)
      return execute_action('add_keywords', args, &block)
    end

    def delete_keywords(*args, &block)
      return execute_action('delete_keywords', args, &block)
    end

    def get_keywords_by_editorial_status(*args, &block)
      return execute_action('get_keywords_by_editorial_status', args, &block)
    end

    def get_keywords_by_ids(*args, &block)
      return execute_action('get_keywords_by_ids', args, &block)
    end

    def get_keywords_by_ad_group_id(*args, &block)
      return execute_action('get_keywords_by_ad_group_id', args, &block)
    end

    def update_keywords(*args, &block)
      return execute_action('update_keywords', args, &block)
    end

    def appeal_editorial_rejections(*args, &block)
      return execute_action('appeal_editorial_rejections', args, &block)
    end

    def add_site_placements(*args, &block)
      return execute_action('add_site_placements', args, &block)
    end

    def delete_site_placements(*args, &block)
      return execute_action('delete_site_placements', args, &block)
    end

    def get_site_placements_by_ids(*args, &block)
      return execute_action('get_site_placements_by_ids', args, &block)
    end

    def get_site_placements_by_ad_group_id(*args, &block)
      return execute_action('get_site_placements_by_ad_group_id', args, &block)
    end

    def update_site_placements(*args, &block)
      return execute_action('update_site_placements', args, &block)
    end

    def get_placement_details_for_urls(*args, &block)
      return execute_action('get_placement_details_for_urls', args, &block)
    end

    def get_editorial_reasons_by_ids(*args, &block)
      return execute_action('get_editorial_reasons_by_ids', args, &block)
    end

    def add_ad_extensions(*args, &block)
      return execute_action('add_ad_extensions', args, &block)
    end

    def get_ad_extensions_by_ids(*args, &block)
      return execute_action('get_ad_extensions_by_ids', args, &block)
    end

    def update_ad_extensions(*args, &block)
      return execute_action('update_ad_extensions', args, &block)
    end

    def delete_ad_extensions(*args, &block)
      return execute_action('delete_ad_extensions', args, &block)
    end

    def get_ad_extensions_editorial_reasons(*args, &block)
      return execute_action('get_ad_extensions_editorial_reasons', args, &block)
    end

    def set_ad_extensions_associations(*args, &block)
      return execute_action('set_ad_extensions_associations', args, &block)
    end

    def get_ad_extensions_associations(*args, &block)
      return execute_action('get_ad_extensions_associations', args, &block)
    end

    def delete_ad_extensions_associations(*args, &block)
      return execute_action('delete_ad_extensions_associations', args, &block)
    end

    def get_ad_extension_ids_by_account_id(*args, &block)
      return execute_action('get_ad_extension_ids_by_account_id', args, &block)
    end

    def add_media(*args, &block)
      return execute_action('add_media', args, &block)
    end

    def get_media_by_ids(*args, &block)
      return execute_action('get_media_by_ids', args, &block)
    end

    def get_ad_group_criterions_by_ids(*args, &block)
      return execute_action('get_ad_group_criterions_by_ids', args, &block)
    end

    def get_ad_group_criterions_by_ad_group_id(*args, &block)
      return execute_action('get_ad_group_criterions_by_ad_group_id', args, &block)
    end

    def add_ad_group_criterions(*args, &block)
      return execute_action('add_ad_group_criterions', args, &block)
    end

    def update_ad_group_criterions(*args, &block)
      return execute_action('update_ad_group_criterions', args, &block)
    end

    def delete_ad_group_criterions(*args, &block)
      return execute_action('delete_ad_group_criterions', args, &block)
    end

    def get_bmc_stores_by_customer_id(*args, &block)
      return execute_action('get_bmc_stores_by_customer_id', args, &block)
    end

    private

    def get_service_registry()
      return CampaignManagementServiceRegistry
    end

    def get_module()
      return BingAdsApi::V9::CampaignManagementService
    end
  end
end; end; end
