# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2013, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.3 on 2014-05-12 15:42:40.

require 'bing_ads_api/errors'

module BingAdsApi; module V9; module CustomerBillingService
  class CustomerBillingServiceRegistry
    CUSTOMERBILLINGSERVICE_METHODS = {:get_billing_documents_info=>{:input=>{:name=>"get_billing_documents_info_request", :fields=>[]}, :output=>{:name=>"get_billing_documents_info_response", :fields=>[]}, :original_name=>"GetBillingDocumentsInfo"}, :get_billing_documents=>{:input=>{:name=>"get_billing_documents_request", :fields=>[]}, :output=>{:name=>"get_billing_documents_response", :fields=>[]}, :original_name=>"GetBillingDocuments"}, :get_display_invoices=>{:input=>{:name=>"get_display_invoices_request", :fields=>[]}, :output=>{:name=>"get_display_invoices_response", :fields=>[]}, :original_name=>"GetDisplayInvoices"}, :add_insertion_order=>{:input=>{:name=>"add_insertion_order_request", :fields=>[]}, :output=>{:name=>"add_insertion_order_response", :fields=>[]}, :original_name=>"AddInsertionOrder"}, :update_insertion_order=>{:input=>{:name=>"update_insertion_order_request", :fields=>[]}, :output=>{:name=>"update_insertion_order_response", :fields=>[]}, :original_name=>"UpdateInsertionOrder"}, :get_insertion_orders_by_account=>{:input=>{:name=>"get_insertion_orders_by_account_request", :fields=>[]}, :output=>{:name=>"get_insertion_orders_by_account_response", :fields=>[]}, :original_name=>"GetInsertionOrdersByAccount"}, :search_insertion_orders=>{:input=>{:name=>"search_insertion_orders_request", :fields=>[]}, :output=>{:name=>"search_insertion_orders_response", :fields=>[]}, :original_name=>"SearchInsertionOrders"}, :get_kohio_invoices=>{:input=>{:name=>"get_kohio_invoices_request", :fields=>[]}, :output=>{:name=>"get_kohio_invoices_response", :fields=>[]}, :original_name=>"GetKOHIOInvoices"}, :get_account_monthly_spend=>{:input=>{:name=>"get_account_monthly_spend_request", :fields=>[]}, :output=>{:name=>"get_account_monthly_spend_response", :fields=>[]}, :original_name=>"GetAccountMonthlySpend"}}
    CUSTOMERBILLINGSERVICE_TYPES = {}
    CUSTOMERBILLINGSERVICE_NAMESPACES = []

    def self.get_method_signature(method_name)
      return CUSTOMERBILLINGSERVICE_METHODS[method_name.to_sym]
    end

    def self.get_type_signature(type_name)
      return CUSTOMERBILLINGSERVICE_TYPES[type_name.to_sym]
    end

    def self.get_namespace(index)
      return CUSTOMERBILLINGSERVICE_NAMESPACES[index]
    end
  end
end; end; end
