# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2013, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.3 on 2014-05-12 15:42:24.

require 'bing_ads_api/errors'

module BingAdsApi; module V9; module OptimizerService
  class OptimizerServiceRegistry
    OPTIMIZERSERVICE_METHODS = {:get_budget_opportunities=>{:input=>{:name=>"get_budget_opportunities_request", :fields=>[]}, :output=>{:name=>"get_budget_opportunities_response", :fields=>[]}, :original_name=>"GetBudgetOpportunities"}, :get_budget_landscape=>{:input=>{:name=>"get_budget_landscape_request", :fields=>[]}, :output=>{:name=>"get_budget_landscape_response", :fields=>[]}, :original_name=>"GetBudgetLandscape"}, :get_bid_opportunities=>{:input=>{:name=>"get_bid_opportunities_request", :fields=>[]}, :output=>{:name=>"get_bid_opportunities_response", :fields=>[]}, :original_name=>"GetBidOpportunities"}, :get_keyword_opportunities=>{:input=>{:name=>"get_keyword_opportunities_request", :fields=>[]}, :output=>{:name=>"get_keyword_opportunities_response", :fields=>[]}, :original_name=>"GetKeywordOpportunities"}, :get_broad_match_opportunities=>{:input=>{:name=>"get_broad_match_opportunities_request", :fields=>[]}, :output=>{:name=>"get_broad_match_opportunities_response", :fields=>[]}, :original_name=>"GetBroadMatchOpportunities"}, :get_broad_match_search_queries=>{:input=>{:name=>"get_broad_match_search_queries_request", :fields=>[]}, :output=>{:name=>"get_broad_match_search_queries_response", :fields=>[]}, :original_name=>"GetBroadMatchSearchQueries"}, :apply_opportunity_modifiers=>{:input=>{:name=>"apply_opportunity_modifiers_request", :fields=>[]}, :output=>{:name=>"apply_opportunity_modifiers_response", :fields=>[]}, :original_name=>"ApplyOpportunityModifiers"}, :apply_opportunities=>{:input=>{:name=>"apply_opportunities_request", :fields=>[]}, :output=>{:name=>"apply_opportunities_response", :fields=>[]}, :original_name=>"ApplyOpportunities"}}
    OPTIMIZERSERVICE_TYPES = {}
    OPTIMIZERSERVICE_NAMESPACES = []

    def self.get_method_signature(method_name)
      return OPTIMIZERSERVICE_METHODS[method_name.to_sym]
    end

    def self.get_type_signature(type_name)
      return OPTIMIZERSERVICE_TYPES[type_name.to_sym]
    end

    def self.get_namespace(index)
      return OPTIMIZERSERVICE_NAMESPACES[index]
    end
  end
end; end; end
