# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2013, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.9.3 on 2014-05-12 15:42:22.

require 'ads_common_for_bing_ads/savon_service'
require 'bing_ads_api/v9/reporting_service_registry'

module BingAdsApi; module V9; module ReportingService
  class ReportingService < AdsCommonForBingAds::SavonService
    def initialize(config, endpoint)
      namespace = 'https://bingads.microsoft.com/Reporting/v9'
      super(config, endpoint, namespace, :V9)
    end

    def submit_generate_report(*args, &block)
      return execute_action('submit_generate_report', args, &block)
    end

    def poll_generate_report(*args, &block)
      return execute_action('poll_generate_report', args, &block)
    end

    private

    def get_service_registry()
      return ReportingServiceRegistry
    end

    def get_module()
      return BingAdsApi::V9::ReportingService
    end
  end
end; end; end
