# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2012, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.7.3 on 2012-07-04 16:49:53.

require 'adcenter_api/errors'

module AdcenterApi; module V8; module BulkService
  class BulkServiceRegistry
    BULKSERVICE_METHODS = {:download_campaigns_by_account_ids=>{:input=>{:name=>"download_campaigns_by_account_ids_request", :fields=>[]}, :output=>{:name=>"download_campaigns_by_account_ids_response", :fields=>[]}, :original_name=>"DownloadCampaignsByAccountIds"}, :download_campaigns_by_campaign_ids=>{:input=>{:name=>"download_campaigns_by_campaign_ids_request", :fields=>[]}, :output=>{:name=>"download_campaigns_by_campaign_ids_response", :fields=>[]}, :original_name=>"DownloadCampaignsByCampaignIds"}, :get_download_status=>{:input=>{:name=>"get_download_status_request", :fields=>[]}, :output=>{:name=>"get_download_status_response", :fields=>[]}, :original_name=>"GetDownloadStatus"}}
    BULKSERVICE_TYPES = {}
    BULKSERVICE_NAMESPACES = []

    def self.get_method_signature(method_name)
      return BULKSERVICE_METHODS[method_name.to_sym]
    end

    def self.get_type_signature(type_name)
      return BULKSERVICE_TYPES[type_name.to_sym]
    end

    def self.get_namespace(index)
      return BULKSERVICE_NAMESPACES[index]
    end
  end
end; end; end
