# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2012, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.7.3 on 2012-07-04 16:50:31.

require 'adcenter_api/errors'

module AdcenterApi; module V8; module OptimizerService
  class OptimizerServiceRegistry
    OPTIMIZERSERVICE_METHODS = {:get_budget_opportunities=>{:input=>{:name=>"get_budget_opportunities_request", :fields=>[]}, :output=>{:name=>"get_budget_opportunities_response", :fields=>[]}, :original_name=>"GetBudgetOpportunities"}, :get_bid_opportunities=>{:input=>{:name=>"get_bid_opportunities_request", :fields=>[]}, :output=>{:name=>"get_bid_opportunities_response", :fields=>[]}, :original_name=>"GetBidOpportunities"}, :apply_budget_opportunities=>{:input=>{:name=>"apply_budget_opportunities_request", :fields=>[]}, :output=>{:name=>"apply_budget_opportunities_response", :fields=>[]}, :original_name=>"ApplyBudgetOpportunities"}, :apply_opportunities=>{:input=>{:name=>"apply_opportunities_request", :fields=>[]}, :output=>{:name=>"apply_opportunities_response", :fields=>[]}, :original_name=>"ApplyOpportunities"}}
    OPTIMIZERSERVICE_TYPES = {}
    OPTIMIZERSERVICE_NAMESPACES = []

    def self.get_method_signature(method_name)
      return OPTIMIZERSERVICE_METHODS[method_name.to_sym]
    end

    def self.get_type_signature(type_name)
      return OPTIMIZERSERVICE_TYPES[type_name.to_sym]
    end

    def self.get_namespace(index)
      return OPTIMIZERSERVICE_NAMESPACES[index]
    end
  end
end; end; end
