# Encoding: utf-8
#
# This is auto-generated code, changes will be overwritten.
#
# Copyright:: Copyright 2012, Google Inc. All Rights Reserved.
# License:: Licensed under the Apache License, Version 2.0.
#
# Code generated by AdsCommon library 0.7.3 on 2012-07-04 16:50:31.

require 'ads_common_for_adcenter/savon_service'
require 'adcenter_api/v8/optimizer_service_registry'

module AdcenterApi; module V8; module OptimizerService
  class OptimizerService < AdsCommonForAdcenter::SavonService
    def initialize(config, endpoint)
      namespace = 'https://adcenter.microsoft.com/v8'
      super(config, endpoint, namespace, :v8)
    end

    def get_budget_opportunities(*args, &block)
      return execute_action('get_budget_opportunities', args, &block)
    end

    def get_bid_opportunities(*args, &block)
      return execute_action('get_bid_opportunities', args, &block)
    end

    def apply_budget_opportunities(*args, &block)
      return execute_action('apply_budget_opportunities', args, &block)
    end

    def apply_opportunities(*args, &block)
      return execute_action('apply_opportunities', args, &block)
    end

    private

    def get_service_registry()
      return OptimizerServiceRegistry
    end

    def get_module()
      return AdcenterApi::V8::OptimizerService
    end
  end
end; end; end
